// Generated by gencpp from file prometheus_msgs/AttitudeReference.msg
// DO NOT EDIT!


#ifndef PROMETHEUS_MSGS_MESSAGE_ATTITUDEREFERENCE_H
#define PROMETHEUS_MSGS_MESSAGE_ATTITUDEREFERENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace prometheus_msgs
{
template <class ContainerAllocator>
struct AttitudeReference_
{
  typedef AttitudeReference_<ContainerAllocator> Type;

  AttitudeReference_()
    : header()
    , throttle_sp()
    , desired_throttle(0.0)
    , desired_attitude()
    , desired_att_q()  {
      throttle_sp.assign(0.0);

      desired_attitude.assign(0.0);
  }
  AttitudeReference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle_sp()
    , desired_throttle(0.0)
    , desired_attitude()
    , desired_att_q(_alloc)  {
  (void)_alloc;
      throttle_sp.assign(0.0);

      desired_attitude.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _throttle_sp_type;
  _throttle_sp_type throttle_sp;

   typedef float _desired_throttle_type;
  _desired_throttle_type desired_throttle;

   typedef boost::array<float, 3>  _desired_attitude_type;
  _desired_attitude_type desired_attitude;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _desired_att_q_type;
  _desired_att_q_type desired_att_q;





  typedef boost::shared_ptr< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> const> ConstPtr;

}; // struct AttitudeReference_

typedef ::prometheus_msgs::AttitudeReference_<std::allocator<void> > AttitudeReference;

typedef boost::shared_ptr< ::prometheus_msgs::AttitudeReference > AttitudeReferencePtr;
typedef boost::shared_ptr< ::prometheus_msgs::AttitudeReference const> AttitudeReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prometheus_msgs::AttitudeReference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prometheus_msgs::AttitudeReference_<ContainerAllocator1> & lhs, const ::prometheus_msgs::AttitudeReference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.throttle_sp == rhs.throttle_sp &&
    lhs.desired_throttle == rhs.desired_throttle &&
    lhs.desired_attitude == rhs.desired_attitude &&
    lhs.desired_att_q == rhs.desired_att_q;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prometheus_msgs::AttitudeReference_<ContainerAllocator1> & lhs, const ::prometheus_msgs::AttitudeReference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prometheus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e58702438e0c601131590714878133df";
  }

  static const char* value(const ::prometheus_msgs::AttitudeReference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe58702438e0c6011ULL;
  static const uint64_t static_value2 = 0x31590714878133dfULL;
};

template<class ContainerAllocator>
struct DataType< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prometheus_msgs/AttitudeReference";
  }

  static const char* value(const ::prometheus_msgs::AttitudeReference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 位置控制器输出： 期望油门 + 期望角度\n"
"float32[3] throttle_sp                 ## [0-1] 惯性系下的油门量\n"
"float32 desired_throttle               ## [0-1] 机体系z轴\n"
"float32[3] desired_attitude            ## [rad]\n"
"geometry_msgs/Quaternion desired_att_q ## 四元数\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::prometheus_msgs::AttitudeReference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle_sp);
      stream.next(m.desired_throttle);
      stream.next(m.desired_attitude);
      stream.next(m.desired_att_q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttitudeReference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prometheus_msgs::AttitudeReference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prometheus_msgs::AttitudeReference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "throttle_sp[]" << std::endl;
    for (size_t i = 0; i < v.throttle_sp.size(); ++i)
    {
      s << indent << "  throttle_sp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.throttle_sp[i]);
    }
    s << indent << "desired_throttle: ";
    Printer<float>::stream(s, indent + "  ", v.desired_throttle);
    s << indent << "desired_attitude[]" << std::endl;
    for (size_t i = 0; i < v.desired_attitude.size(); ++i)
    {
      s << indent << "  desired_attitude[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.desired_attitude[i]);
    }
    s << indent << "desired_att_q: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.desired_att_q);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROMETHEUS_MSGS_MESSAGE_ATTITUDEREFERENCE_H
